# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b2f678ce3b16f16d13f7d7d4f1fdff8c3dd28a69d278f0ca7ea44dffc91984efb5542bde34ca264541767b73f16430591330d182a227adebbfe6e358c3b10d77

test:
  secret_key_base: f796f0b299f6e8e86f983d321f768b0b9ac3703f350ad3173f620d4aa9fe659729ce2d214e1183736a428c88d051c9acfe803d61d950f1d0dbdf0f2d7d61edd8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
